[build]
builder = "NIXPACKS"
nixpacksPkgs = ["zlib", "libjpeg", "libpng"]

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
sleepApplication = false
restartPolicyMaxRetries = 10